sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20031224yyb
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: 20031224yyb
#    access-key-secret: 20031224yyb
#    bucket-name: javaweb-yyb
  redis:
    host: localhost
    port: 6379
    password: 20031224yyb
    database: 0
  wechat:
    appid: wxa4939d8afd021984
    secret: ca9e59c43b4c0a7fab372ec4c3e7995d